spring.profiles.active: dev
spring.application.name: demo-rest
spring.output.ansi.enabled: never
xo.cache.config-file: redisson-${spring.profiles.active}.yml
xo.api.doc:
  title: 后台管理服务
  description: 后台管理服务接口
  version: 1.0
  base-package: com.github.jnoee.xo.starter.demo.api
logging:
  level:
    root: warn