spring.datasource.druid:
  url: jdbc:mysql://localhost:3306/demo?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF8
  username: root
  password: null
  initial-size: 5
  min-idle: 10
  max-active: 50
spring.jpa:
  database: mysql
  show-sql: false
logging:
  file: ./logs/xo-demo-dwz.log
  level:
    com.github.jnoee: info
