spring.h2.console.enabled: true
spring.datasource.druid:
  url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
  username: sa
  password: null
spring.jpa:
  database: h2
  show-sql: true
  properties:
    hibernate.search.default.elasticsearch.host: http://localhost:9200
logging:
  level:
    com.github.jnoee: debug